/* ══════════════════════════════════════════════════════
   rehla-lang.js — نظام اللغة الموحد لمشروع رحلة+
   يدعم: العربية، الإنجليزية، الهندية، الفرنسية، الألمانية، التركية
══════════════════════════════════════════════════════ */

const REHLA_LANGS = {

  /* ══ العربية ══ */
  ar: {
    dir: 'rtl', font: 'Cairo',
    // NAV
    nav_login: 'تسجيل الدخول',
    nav_start: 'ابدأ رحلة جديدة',
    nav_features: 'المزايا',
    nav_how: 'كيف يعمل؟',
    nav_pricing: 'الأسعار',
    nav_contact: 'تواصل معنا',
    // DASHBOARD NAV
    nav_dashboard: '🏠 لوحة الرحلة',
    nav_expenses: '💳 المصاريف',
    nav_receipts: '📸 الإيصالات',
    nav_summary: '📊 الملخص المالي',
    nav_settle: '🧮 تصفية الحساب',
    nav_report: '📄 التقرير',
    nav_members: '👥 الأعضاء والأدوار',
    nav_share: '🔗 مشاركة الرحلة',
    nav_settings: '⚙ الإعدادات',
    // TOPBAR
    topbar_share: '🔗 مشاركة',
    topbar_add: '+ إضافة مصروف',
    // NAV SECTIONS
    sec_main: 'الرئيسية',
    sec_expenses: 'المصاريف',
    sec_analysis: 'التحليل',
    sec_members: 'الأعضاء',
    // KPIs
    kpi_total: 'إجمالي المصاريف',
    kpi_per: 'نصيب كل شخص',
    kpi_top: 'الأكثر دفعاً',
    kpi_members: 'عدد الأعضاء',
    kpi_approx: 'تقريباً',
    kpi_participant: 'مشارك في الرحلة',
    // PAGES TITLES
    page_dashboard: 'لوحة الرحلة',
    page_expenses: 'المصاريف',
    page_summary: 'الملخص المالي',
    page_settle: 'تصفية الحساب',
    page_report: 'التقرير',
    page_members: 'الأعضاء والأدوار',
    page_share: 'مشاركة الرحلة',
    page_settings: 'الإعدادات',
    page_receipts: 'الإيصالات',
    // EXPENSE MODAL
    modal_add_exp: 'إضافة مصروف جديد',
    modal_edit_exp: 'تعديل المصروف',
    exp_name: 'اسم المصروف *',
    exp_amount: 'المبلغ *',
    exp_paid_by: 'من دفع؟ *',
    exp_date: 'التاريخ',
    exp_category: 'التصنيف',
    exp_note: 'ملاحظة (اختياري)',
    exp_dist: 'التوزيع على',
    exp_all: 'الجميع',
    exp_specific: 'أشخاص محددين',
    btn_save: 'حفظ المصروف',
    btn_cancel: 'إلغاء',
    btn_delete: 'حذف',
    btn_edit: 'تعديل',
    btn_add: 'إضافة',
    // MEMBERS
    add_member: 'إضافة عضو',
    member_name: 'اسم العضو',
    member_phone: 'رقم الواتساب',
    member_role: 'الدور',
    add_member_btn: 'إضافة عضو جديد',
    no_members: 'لا يوجد أعضاء بعد',
    organizer: 'مسؤول الرحلة',
    // SETTLE
    settle_title: 'تصفية الحساب',
    settle_note: 'أقل عدد تحويلات',
    settle_done: 'الحسابات متوازنة! 🎉',
    settle_done_sub: 'لا توجد مبالغ متبقية بين الأعضاء',
    // EMPTY STATES
    no_trips: 'لا توجد رحلات بعد!',
    no_trips_sub: 'أنشئ رحلتك الأولى وابدأ بتتبع المصاريف',
    no_expenses: 'لا توجد مصاريف بعد — أضف أول مصروف!',
    create_trip: '✈ إنشاء رحلة جديدة',
    price_note: '٢٤٩ درهم فقط — دفعة واحدة للرحلة الكاملة',
    // SHARE
    share_link_lbl: 'رابط الرحلة',
    share_link_hint: 'شارك هذا الرابط مع أعضاء الرحلة.',
    share_copy: 'نسخ',
    share_copied: '✓ تم النسخ',
    share_wa: 'واتساب',
    share_wa_title: '📲 إرسال واتساب للأعضاء',
    share_sent: '✓ أُرسل',
    share_not_sent: 'لم يُرسل',
    share_no_phone: 'بدون رقم',
    send_btn: '💬 إرسال',
    // SETTINGS
    settings_trip: '⚙ إعدادات الرحلة',
    settings_theme: '🎨 ثيم الصفحة',
    settings_theme_hint: 'اختر اللون الذي يعجبك — يتغير كل شيء فوراً',
    settings_save: 'حفظ التغييرات',
    settings_saved: 'تم حفظ الإعدادات ✓',
    settings_lang: '🌐 اللغة',
    trip_name: 'اسم الرحلة',
    trip_dest: 'الوجهة',
    trip_start: 'تاريخ البداية',
    trip_end: 'تاريخ النهاية',
    // THEME CATS
    theme_men: '🔵 رجالية — قوية وعميقة',
    theme_women: '🌸 أنثوية — ناعمة وراقية',
    theme_nature: '🌍 الطبيعة والسفر',
    // TOASTS
    toast_added: 'تم إضافة المصروف',
    toast_edited: 'تم تعديل المصروف',
    toast_deleted: 'تم الحذف',
    toast_copied: '✓ تم نسخ الرابط',
    toast_member_added: 'تم إضافة العضو',
    toast_error: 'حدث خطأ',
    toast_fill: 'يرجى ملء الحقول المطلوبة',
    toast_theme: '✓ تم تغيير الثيم',
    // CREATE PAGE
    step1_title: 'تفاصيل رحلتك',
    step1_sub: 'أدخل معلومات الرحلة الأساسية',
    step2_title: 'أضف المرافقين',
    step2_sub: 'حدد أدوار كل مرافق',
    step3_title: 'راجع وأنشئ',
    step3_sub: 'راجع التفاصيل وأنشئ رحلتك',
    sl1: 'تفاصيل الرحلة',
    sl2: 'المرافقون',
    sl3: 'التأكيد',
    next_companions: 'التالي — المرافقون ←',
    next_review: 'التالي — المراجعة ←',
    back: 'رجوع',
    home: 'الرئيسية',
    create_btn: 'إنشاء الرحلة والانطلاق',
    trip_photo: 'صورة الرحلة',
    trip_photo_hint: 'اختياري — وجهتك أو لحظة من السفر',
    choose_photo: 'اختر صورة',
    trip_info: '✈ معلومات الرحلة',
    main_dest: 'الوجهة الرئيسية',
    nights: 'عدد الليالي',
    start_date: 'تاريخ البداية',
    end_date: 'تاريخ النهاية',
    currency: '💱 عملة الرحلة',
    multi_country: 'الرحلة تمر بأكثر من دولة',
    multi_hint: 'أضف الدول مع تواريخ الوصول والمغادرة',
    add_country: 'أضف',
    arrival: 'وصول:',
    departure: 'مغادرة:',
    notes: '📝 ملاحظات',
    org_section: '👑 مسؤول الرحلة (أنت)',
    org_name: 'اسمك الكامل',
    org_phone: 'رقم الواتساب',
    companions_section: '👥 المرافقون',
    comp_total: 'إجمالي المرافقين المضافين',
    comp_form_title: '➕ بيانات المرافق',
    comp_name: 'الاسم',
    comp_phone: 'الواتساب',
    comp_role: 'دور المرافق',
    comp_add_btn: 'إضافة المرافق',
    add_comp: 'إضافة مرافق جديد',
    comp_hint: 'يمكنك إضافة المرافقين لاحقاً من لوحة التحكم',
    // SUMMARY
    sum_countries: 'الدول المضافة',
    sum_member: 'العضو',
    sum_role: 'الدور',
    sum_phone: 'الواتساب',
    what_get: 'ماذا تحصل عليه مقابل ٢٤٩ درهم؟',
    total_pay: 'إجمالي الدفع',
    price_sub: 'درهم إماراتي — رحلة كاملة',
    one_time: 'دفعة واحدة فقط',
    no_sub: 'بدون اشتراك شهري',
    pay_info: 'معلومات الدفع',
    pay_txt: 'سيتم حفظ رحلتك وتفعيلها مباشرة. ربط Stripe للدفع الحقيقي قيد التطوير.',
    // SUCCESS
    suc_title: 'تم إنشاء رحلتك!',
    suc_sub: 'ابدأ بتسجيل المصاريف وشارك الرابط مع رفاقك.',
    suc_ok: 'تم إنشاء الرحلة بنجاح',
    goto_dash: 'انتقل للوحة الرحلة',
    share_link_btn: 'شارك الرابط مع المرافقين',
    // COMPANION PAGE
    trip_view: 'عرض الرحلة',
    loading: 'جاري تحميل بيانات الرحلة...',
    trip_not_found: 'الرحلة غير موجودة',
    trip_not_found_sub: 'تأكد من الرابط أو تواصل مع مسؤول الرحلة',
    total_exp: 'إجمالي المصاريف',
    exp_count: 'عدد المصاريف',
    per_person: 'نصيب كل شخص',
    my_bal: 'رصيدك في الرحلة',
    trip_summary: 'ملخص الرحلة',
    status_active: '● نشطة',
    status_archived: '● مؤرشفة',
    members_lbl: 'أعضاء',
    expenses_lbl: 'مصروف',
    exp_list: 'قائمة المصاريف',
    th_name: 'اسم المصروف',
    th_cat: 'التصنيف',
    th_payer: 'من دفع',
    th_date: 'التاريخ',
    th_amount: 'المبلغ',
    no_exp_yet: 'لا توجد مصاريف بعد',
    all_settled: 'الحسابات متوازنة! لا توجد مبالغ متبقية.',
    footer_txt: 'تم إنشاء هذا الرابط بواسطة مسؤول الرحلة عبر',
    footer_txt2: 'لإنشاء رحلتك الخاصة وتتبع المصاريف',
    footer_link: 'سجّل مجاناً',
    paid: 'دفع:',
    owes: 'عليه:',
    user_role: '👑 مسؤول الرحلة',
  },

  /* ══ English ══ */
  en: {
    dir: 'ltr', font: 'Cairo',
    nav_login: 'Sign In',
    nav_start: 'Start New Trip',
    nav_features: 'Features',
    nav_how: 'How it works?',
    nav_pricing: 'Pricing',
    nav_contact: 'Contact Us',
    nav_dashboard: '🏠 Dashboard',
    nav_expenses: '💳 Expenses',
    nav_receipts: '📸 Receipts',
    nav_summary: '📊 Financial Summary',
    nav_settle: '🧮 Settlement',
    nav_report: '📄 Report',
    nav_members: '👥 Members & Roles',
    nav_share: '🔗 Share Trip',
    nav_settings: '⚙ Settings',
    topbar_share: '🔗 Share',
    topbar_add: '+ Add Expense',
    sec_main: 'Main',
    sec_expenses: 'Expenses',
    sec_analysis: 'Analysis',
    sec_members: 'Members',
    kpi_total: 'Total Expenses',
    kpi_per: 'Per Person',
    kpi_top: 'Top Payer',
    kpi_members: 'Members',
    kpi_approx: 'approx.',
    kpi_participant: 'trip participants',
    page_dashboard: 'Dashboard',
    page_expenses: 'Expenses',
    page_summary: 'Financial Summary',
    page_settle: 'Settlement',
    page_report: 'Report',
    page_members: 'Members & Roles',
    page_share: 'Share Trip',
    page_settings: 'Settings',
    page_receipts: 'Receipts',
    modal_add_exp: 'Add New Expense',
    modal_edit_exp: 'Edit Expense',
    exp_name: 'Expense Name *',
    exp_amount: 'Amount *',
    exp_paid_by: 'Paid by? *',
    exp_date: 'Date',
    exp_category: 'Category',
    exp_note: 'Note (optional)',
    exp_dist: 'Split for',
    exp_all: 'Everyone',
    exp_specific: 'Specific people',
    btn_save: 'Save Expense',
    btn_cancel: 'Cancel',
    btn_delete: 'Delete',
    btn_edit: 'Edit',
    btn_add: 'Add',
    add_member: 'Add Member',
    member_name: 'Member Name',
    member_phone: 'WhatsApp Number',
    member_role: 'Role',
    add_member_btn: 'Add New Member',
    no_members: 'No members yet',
    organizer: 'Trip Organizer',
    settle_title: 'Settlement',
    settle_note: 'Minimum transfers',
    settle_done: 'All settled! 🎉',
    settle_done_sub: 'No outstanding balances between members',
    no_trips: 'No trips yet!',
    no_trips_sub: 'Create your first trip and start tracking expenses',
    no_expenses: 'No expenses yet — add your first!',
    create_trip: '✈ Create New Trip',
    price_note: '249 AED only — one-time payment',
    share_link_lbl: 'Trip Link',
    share_link_hint: 'Share this link with your trip members.',
    share_copy: 'Copy',
    share_copied: '✓ Copied',
    share_wa: 'WhatsApp',
    share_wa_title: '📲 Send WhatsApp to Members',
    share_sent: '✓ Sent',
    share_not_sent: 'Not sent',
    share_no_phone: 'No number',
    send_btn: '💬 Send',
    settings_trip: '⚙ Trip Settings',
    settings_theme: '🎨 Page Theme',
    settings_theme_hint: 'Choose your color — everything changes instantly',
    settings_save: 'Save Changes',
    settings_saved: 'Settings saved ✓',
    settings_lang: '🌐 Language',
    trip_name: 'Trip Name',
    trip_dest: 'Destination',
    trip_start: 'Start Date',
    trip_end: 'End Date',
    theme_men: '🔵 Bold — Deep & Strong',
    theme_women: '🌸 Elegant — Soft & Refined',
    theme_nature: '🌍 Nature & Travel',
    toast_added: 'Expense added',
    toast_edited: 'Expense updated',
    toast_deleted: 'Deleted',
    toast_copied: '✓ Link copied',
    toast_member_added: 'Member added',
    toast_error: 'An error occurred',
    toast_fill: 'Please fill required fields',
    toast_theme: '✓ Theme changed',
    step1_title: 'Trip Details',
    step1_sub: 'Enter basic trip information',
    step2_title: 'Add Companions',
    step2_sub: "Define each companion's role",
    step3_title: 'Review & Create',
    step3_sub: 'Review details and create your trip',
    sl1: 'Trip Details',
    sl2: 'Companions',
    sl3: 'Confirm',
    next_companions: 'Next — Companions →',
    next_review: 'Next — Review →',
    back: 'Back',
    home: 'Home',
    create_btn: 'Create Trip & Go',
    trip_photo: 'Trip Photo',
    trip_photo_hint: 'Optional — your destination or a travel moment',
    choose_photo: 'Choose Photo',
    trip_info: '✈ Trip Info',
    main_dest: 'Main Destination',
    nights: 'Nights',
    start_date: 'Start Date',
    end_date: 'End Date',
    currency: '💱 Trip Currency',
    multi_country: 'Multi-country trip',
    multi_hint: 'Add countries with arrival & departure dates',
    add_country: 'Add',
    arrival: 'Arrival:',
    departure: 'Departure:',
    notes: '📝 Notes',
    org_section: '👑 Trip Organizer (You)',
    org_name: 'Your Full Name',
    org_phone: 'WhatsApp Number',
    companions_section: '👥 Companions',
    comp_total: 'Total companions added',
    comp_form_title: '➕ Companion Details',
    comp_name: 'Name',
    comp_phone: 'WhatsApp',
    comp_role: 'Role',
    comp_add_btn: 'Add Companion',
    add_comp: 'Add New Companion',
    comp_hint: 'You can add companions later from the dashboard',
    sum_countries: 'Added Countries',
    sum_member: 'Member',
    sum_role: 'Role',
    sum_phone: 'WhatsApp',
    what_get: 'What you get for 249 AED?',
    total_pay: 'Total Payment',
    price_sub: 'AED — full trip access',
    one_time: 'One-time payment',
    no_sub: 'No monthly subscription',
    pay_info: 'Payment Info',
    pay_txt: 'Your trip will be saved and activated immediately. Stripe integration coming soon.',
    suc_title: 'Trip Created!',
    suc_sub: 'Start logging expenses and share the link with your companions.',
    suc_ok: 'Trip created successfully',
    goto_dash: 'Go to Dashboard',
    share_link_btn: 'Share link with companions',
    trip_view: 'Trip View',
    loading: 'Loading trip data...',
    trip_not_found: 'Trip Not Found',
    trip_not_found_sub: 'Check the link or contact the trip organizer',
    total_exp: 'Total Expenses',
    exp_count: 'Expenses Count',
    per_person: 'Per Person',
    my_bal: 'Your Balance',
    trip_summary: 'Trip Summary',
    status_active: '● Active',
    status_archived: '● Archived',
    members_lbl: 'members',
    expenses_lbl: 'expenses',
    exp_list: 'Expenses List',
    th_name: 'Expense',
    th_cat: 'Category',
    th_payer: 'Paid by',
    th_date: 'Date',
    th_amount: 'Amount',
    no_exp_yet: 'No expenses yet',
    all_settled: 'All settled! No outstanding balances.',
    footer_txt: 'This link was created by the trip organizer via',
    footer_txt2: 'To create your own trip and track expenses',
    footer_link: 'Sign up free',
    paid: 'Paid:',
    owes: 'Owes:',
    user_role: '👑 Trip Organizer',
  },

  /* ══ हिन्दी — Hindi ══ */
  hi: {
    dir: 'ltr', font: 'Noto Sans',
    nav_login: 'साइन इन',
    nav_start: 'नई यात्रा शुरू करें',
    nav_features: 'विशेषताएं',
    nav_how: 'यह कैसे काम करता है?',
    nav_pricing: 'मूल्य',
    nav_contact: 'संपर्क करें',
    nav_dashboard: '🏠 डैशबोर्ड',
    nav_expenses: '💳 खर्च',
    nav_receipts: '📸 रसीदें',
    nav_summary: '📊 वित्तीय सारांश',
    nav_settle: '🧮 निपटान',
    nav_report: '📄 रिपोर्ट',
    nav_members: '👥 सदस्य और भूमिकाएं',
    nav_share: '🔗 यात्रा साझा करें',
    nav_settings: '⚙ सेटिंग्स',
    topbar_share: '🔗 साझा करें',
    topbar_add: '+ खर्च जोड़ें',
    sec_main: 'मुख्य',
    sec_expenses: 'खर्च',
    sec_analysis: 'विश्लेषण',
    sec_members: 'सदस्य',
    kpi_total: 'कुल खर्च',
    kpi_per: 'प्रति व्यक्ति',
    kpi_top: 'सबसे अधिक भुगतानकर्ता',
    kpi_members: 'सदस्य',
    kpi_approx: 'लगभग',
    kpi_participant: 'यात्रा प्रतिभागी',
    page_dashboard: 'डैशबोर्ड',
    page_expenses: 'खर्च',
    page_summary: 'वित्तीय सारांश',
    page_settle: 'निपटान',
    page_report: 'रिपोर्ट',
    page_members: 'सदस्य और भूमिकाएं',
    page_share: 'यात्रा साझा करें',
    page_settings: 'सेटिंग्स',
    page_receipts: 'रसीदें',
    modal_add_exp: 'नया खर्च जोड़ें',
    modal_edit_exp: 'खर्च संपादित करें',
    exp_name: 'खर्च का नाम *',
    exp_amount: 'राशि *',
    exp_paid_by: 'किसने भुगतान किया? *',
    exp_date: 'तारीख',
    exp_category: 'श्रेणी',
    exp_note: 'नोट (वैकल्पिक)',
    exp_dist: 'विभाजित करें',
    exp_all: 'सभी',
    exp_specific: 'विशिष्ट लोग',
    btn_save: 'खर्च सहेजें',
    btn_cancel: 'रद्द करें',
    btn_delete: 'हटाएं',
    btn_edit: 'संपादित करें',
    btn_add: 'जोड़ें',
    add_member: 'सदस्य जोड़ें',
    member_name: 'सदस्य का नाम',
    member_phone: 'व्हाट्सएप नंबर',
    member_role: 'भूमिका',
    add_member_btn: 'नया सदस्य जोड़ें',
    no_members: 'अभी तक कोई सदस्य नहीं',
    organizer: 'यात्रा आयोजक',
    settle_title: 'निपटान',
    settle_note: 'न्यूनतम लेनदेन',
    settle_done: 'सब निपट गया! 🎉',
    settle_done_sub: 'सदस्यों के बीच कोई बकाया नहीं',
    no_trips: 'अभी तक कोई यात्रा नहीं!',
    no_trips_sub: 'अपनी पहली यात्रा बनाएं',
    no_expenses: 'अभी तक कोई खर्च नहीं',
    create_trip: '✈ नई यात्रा बनाएं',
    price_note: 'केवल 249 AED — एकमुश्त भुगतान',
    share_link_lbl: 'यात्रा लिंक',
    share_link_hint: 'इस लिंक को सदस्यों के साथ साझा करें।',
    share_copy: 'कॉपी करें',
    share_copied: '✓ कॉपी हो गया',
    share_wa: 'व्हाट्सएप',
    share_wa_title: '📲 व्हाट्सएप भेजें',
    share_sent: '✓ भेजा गया',
    share_not_sent: 'नहीं भेजा',
    share_no_phone: 'नंबर नहीं',
    send_btn: '💬 भेजें',
    settings_trip: '⚙ यात्रा सेटिंग्स',
    settings_theme: '🎨 पेज थीम',
    settings_theme_hint: 'अपना रंग चुनें — सब कुछ तुरंत बदल जाता है',
    settings_save: 'परिवर्तन सहेजें',
    settings_saved: 'सेटिंग्स सहेजी गई ✓',
    settings_lang: '🌐 भाषा',
    trip_name: 'यात्रा का नाम',
    trip_dest: 'गंतव्य',
    trip_start: 'प्रारंभ तिथि',
    trip_end: 'समाप्ति तिथि',
    theme_men: '🔵 बोल्ड — गहरा और मजबूत',
    theme_women: '🌸 सुंदर — कोमल और परिष्कृत',
    theme_nature: '🌍 प्रकृति और यात्रा',
    toast_added: 'खर्च जोड़ा गया',
    toast_edited: 'खर्च अपडेट किया गया',
    toast_deleted: 'हटा दिया गया',
    toast_copied: '✓ लिंक कॉपी हो गया',
    toast_member_added: 'सदस्य जोड़ा गया',
    toast_error: 'एक त्रुटि हुई',
    toast_fill: 'कृपया आवश्यक फ़ील्ड भरें',
    toast_theme: '✓ थीम बदली गई',
    step1_title: 'यात्रा विवरण',
    step1_sub: 'बुनियादी यात्रा जानकारी दर्ज करें',
    step2_title: 'साथी जोड़ें',
    step2_sub: 'प्रत्येक साथी की भूमिका परिभाषित करें',
    step3_title: 'समीक्षा और बनाएं',
    step3_sub: 'विवरण की समीक्षा करें',
    sl1: 'यात्रा विवरण', sl2: 'साथी', sl3: 'पुष्टि करें',
    next_companions: 'अगला — साथी →',
    next_review: 'अगला — समीक्षा →',
    back: 'वापस', home: 'होम',
    create_btn: 'यात्रा बनाएं और जाएं',
    org_name: 'आपका पूरा नाम', org_phone: 'व्हाट्सएप नंबर',
    organizer_badge: '👑 आयोजक',
    user_role: '👑 यात्रा आयोजक',
    paid: 'भुगतान:', owes: 'बकाया:',
    total_exp: 'कुल खर्च', exp_count: 'खर्च की संख्या',
    per_person: 'प्रति व्यक्ति', trip_summary: 'यात्रा सारांश',
    status_active: '● सक्रिय', status_archived: '● संग्रहीत',
    members_lbl: 'सदस्य', expenses_lbl: 'खर्च',
    settle_title: 'निपटान', settle_note: 'न्यूनतम लेनदेन',
    all_settled: 'सब निपट गया! कोई बकाया नहीं।',
    loading: 'यात्रा डेटा लोड हो रहा है...',
    trip_not_found: 'यात्रा नहीं मिली',
    trip_not_found_sub: 'लिंक जांचें या यात्रा आयोजक से संपर्क करें',
    footer_link: 'मुफ्त साइन अप करें',
  },

  /* ══ Français — French ══ */
  fr: {
    dir: 'ltr', font: 'Cairo',
    nav_login: 'Connexion',
    nav_start: 'Nouveau voyage',
    nav_features: 'Fonctionnalités',
    nav_how: 'Comment ça marche?',
    nav_pricing: 'Tarifs',
    nav_contact: 'Contact',
    nav_dashboard: '🏠 Tableau de bord',
    nav_expenses: '💳 Dépenses',
    nav_receipts: '📸 Reçus',
    nav_summary: '📊 Résumé financier',
    nav_settle: '🧮 Règlement',
    nav_report: '📄 Rapport',
    nav_members: '👥 Membres et rôles',
    nav_share: '🔗 Partager le voyage',
    nav_settings: '⚙ Paramètres',
    topbar_share: '🔗 Partager',
    topbar_add: '+ Ajouter dépense',
    sec_main: 'Principal',
    sec_expenses: 'Dépenses',
    sec_analysis: 'Analyse',
    sec_members: 'Membres',
    kpi_total: 'Total des dépenses',
    kpi_per: 'Par personne',
    kpi_top: 'Payeur principal',
    kpi_members: 'Membres',
    kpi_approx: 'environ',
    kpi_participant: 'participants',
    page_dashboard: 'Tableau de bord',
    page_expenses: 'Dépenses',
    page_summary: 'Résumé financier',
    page_settle: 'Règlement',
    page_report: 'Rapport',
    page_members: 'Membres et rôles',
    page_share: 'Partager le voyage',
    page_settings: 'Paramètres',
    page_receipts: 'Reçus',
    modal_add_exp: 'Ajouter une dépense',
    modal_edit_exp: 'Modifier la dépense',
    exp_name: 'Nom de la dépense *',
    exp_amount: 'Montant *',
    exp_paid_by: 'Payé par? *',
    exp_date: 'Date',
    exp_category: 'Catégorie',
    exp_note: 'Note (optionnelle)',
    exp_dist: 'Répartir pour',
    exp_all: 'Tout le monde',
    exp_specific: 'Personnes spécifiques',
    btn_save: 'Enregistrer',
    btn_cancel: 'Annuler',
    btn_delete: 'Supprimer',
    btn_edit: 'Modifier',
    btn_add: 'Ajouter',
    add_member: 'Ajouter membre',
    member_name: 'Nom du membre',
    member_phone: 'WhatsApp',
    member_role: 'Rôle',
    add_member_btn: 'Nouveau membre',
    no_members: 'Aucun membre',
    organizer: 'Organisateur',
    settle_title: 'Règlement',
    settle_note: 'Transferts minimaux',
    settle_done: 'Tout réglé! 🎉',
    settle_done_sub: 'Aucun solde en attente',
    no_trips: 'Aucun voyage!',
    no_trips_sub: 'Créez votre premier voyage',
    no_expenses: 'Aucune dépense — ajoutez la première!',
    create_trip: '✈ Créer un voyage',
    price_note: '249 AED seulement — paiement unique',
    share_copy: 'Copier',
    share_copied: '✓ Copié',
    share_wa: 'WhatsApp',
    send_btn: '💬 Envoyer',
    settings_trip: '⚙ Paramètres du voyage',
    settings_theme: '🎨 Thème',
    settings_theme_hint: 'Choisissez votre couleur — tout change instantanément',
    settings_save: 'Enregistrer',
    settings_saved: 'Paramètres enregistrés ✓',
    settings_lang: '🌐 Langue',
    trip_name: 'Nom du voyage',
    trip_dest: 'Destination',
    trip_start: 'Date de début',
    trip_end: 'Date de fin',
    theme_men: '🔵 Audacieux — Profond et fort',
    theme_women: '🌸 Élégant — Doux et raffiné',
    theme_nature: '🌍 Nature et voyage',
    toast_added: 'Dépense ajoutée',
    toast_edited: 'Dépense modifiée',
    toast_deleted: 'Supprimé',
    toast_copied: '✓ Lien copié',
    toast_member_added: 'Membre ajouté',
    toast_error: 'Une erreur s\'est produite',
    toast_fill: 'Veuillez remplir les champs requis',
    toast_theme: '✓ Thème changé',
    back: 'Retour', home: 'Accueil',
    create_btn: 'Créer le voyage',
    user_role: '👑 Organisateur',
    paid: 'Payé:', owes: 'Doit:',
    total_exp: 'Total', exp_count: 'Dépenses',
    per_person: 'Par personne', trip_summary: 'Résumé',
    status_active: '● Actif', status_archived: '● Archivé',
    members_lbl: 'membres', expenses_lbl: 'dépenses',
    all_settled: 'Tout réglé! Aucun solde en attente.',
    loading: 'Chargement des données...',
    trip_not_found: 'Voyage introuvable',
    trip_not_found_sub: 'Vérifiez le lien ou contactez l\'organisateur',
    footer_link: 'Inscription gratuite',
  },

  /* ══ Deutsch — German ══ */
  de: {
    dir: 'ltr', font: 'Cairo',
    nav_login: 'Anmelden',
    nav_start: 'Neue Reise',
    nav_features: 'Funktionen',
    nav_how: 'Wie es funktioniert?',
    nav_pricing: 'Preise',
    nav_contact: 'Kontakt',
    nav_dashboard: '🏠 Dashboard',
    nav_expenses: '💳 Ausgaben',
    nav_receipts: '📸 Belege',
    nav_summary: '📊 Finanzübersicht',
    nav_settle: '🧮 Abrechnung',
    nav_report: '📄 Bericht',
    nav_members: '👥 Mitglieder & Rollen',
    nav_share: '🔗 Reise teilen',
    nav_settings: '⚙ Einstellungen',
    topbar_share: '🔗 Teilen',
    topbar_add: '+ Ausgabe hinzufügen',
    sec_main: 'Haupt',
    sec_expenses: 'Ausgaben',
    sec_analysis: 'Analyse',
    sec_members: 'Mitglieder',
    kpi_total: 'Gesamtausgaben',
    kpi_per: 'Pro Person',
    kpi_top: 'Hauptzahler',
    kpi_members: 'Mitglieder',
    kpi_approx: 'ca.',
    kpi_participant: 'Teilnehmer',
    page_dashboard: 'Dashboard',
    page_expenses: 'Ausgaben',
    page_summary: 'Finanzübersicht',
    page_settle: 'Abrechnung',
    page_report: 'Bericht',
    page_members: 'Mitglieder & Rollen',
    page_share: 'Reise teilen',
    page_settings: 'Einstellungen',
    page_receipts: 'Belege',
    modal_add_exp: 'Ausgabe hinzufügen',
    modal_edit_exp: 'Ausgabe bearbeiten',
    exp_name: 'Ausgabenname *',
    exp_amount: 'Betrag *',
    exp_paid_by: 'Bezahlt von? *',
    exp_date: 'Datum',
    exp_category: 'Kategorie',
    exp_note: 'Notiz (optional)',
    exp_dist: 'Aufteilen für',
    exp_all: 'Alle',
    exp_specific: 'Bestimmte Personen',
    btn_save: 'Speichern',
    btn_cancel: 'Abbrechen',
    btn_delete: 'Löschen',
    btn_edit: 'Bearbeiten',
    btn_add: 'Hinzufügen',
    add_member: 'Mitglied hinzufügen',
    member_name: 'Mitgliedsname',
    member_phone: 'WhatsApp',
    member_role: 'Rolle',
    add_member_btn: 'Neues Mitglied',
    no_members: 'Keine Mitglieder',
    organizer: 'Organisator',
    settle_title: 'Abrechnung',
    settle_note: 'Minimale Überweisungen',
    settle_done: 'Alles beglichen! 🎉',
    settle_done_sub: 'Keine ausstehenden Salden',
    no_trips: 'Noch keine Reisen!',
    no_trips_sub: 'Erstellen Sie Ihre erste Reise',
    no_expenses: 'Noch keine Ausgaben',
    create_trip: '✈ Neue Reise erstellen',
    price_note: 'Nur 249 AED — Einmalzahlung',
    share_copy: 'Kopieren',
    share_copied: '✓ Kopiert',
    share_wa: 'WhatsApp',
    send_btn: '💬 Senden',
    settings_trip: '⚙ Reiseeinstellungen',
    settings_theme: '🎨 Seitenthema',
    settings_theme_hint: 'Wählen Sie Ihre Farbe — alles ändert sich sofort',
    settings_save: 'Speichern',
    settings_saved: 'Einstellungen gespeichert ✓',
    settings_lang: '🌐 Sprache',
    trip_name: 'Reisename',
    trip_dest: 'Reiseziel',
    trip_start: 'Startdatum',
    trip_end: 'Enddatum',
    theme_men: '🔵 Mutig — Tief und stark',
    theme_women: '🌸 Elegant — Sanft und verfeinert',
    theme_nature: '🌍 Natur und Reise',
    toast_added: 'Ausgabe hinzugefügt',
    toast_edited: 'Ausgabe aktualisiert',
    toast_deleted: 'Gelöscht',
    toast_copied: '✓ Link kopiert',
    toast_member_added: 'Mitglied hinzugefügt',
    toast_error: 'Ein Fehler ist aufgetreten',
    toast_fill: 'Bitte füllen Sie die Pflichtfelder aus',
    toast_theme: '✓ Thema geändert',
    back: 'Zurück', home: 'Startseite',
    create_btn: 'Reise erstellen',
    user_role: '👑 Organisator',
    paid: 'Gezahlt:', owes: 'Schuldet:',
    total_exp: 'Gesamt', exp_count: 'Ausgaben',
    per_person: 'Pro Person', trip_summary: 'Zusammenfassung',
    status_active: '● Aktiv', status_archived: '● Archiviert',
    members_lbl: 'Mitglieder', expenses_lbl: 'Ausgaben',
    all_settled: 'Alles beglichen! Keine ausstehenden Salden.',
    loading: 'Reisedaten werden geladen...',
    trip_not_found: 'Reise nicht gefunden',
    trip_not_found_sub: 'Überprüfen Sie den Link oder kontaktieren Sie den Organisator',
    footer_link: 'Kostenlos registrieren',
  },

  /* ══ Türkçe — Turkish ══ */
  tr: {
    dir: 'ltr', font: 'Cairo',
    nav_login: 'Giriş Yap',
    nav_start: 'Yeni Seyahat',
    nav_features: 'Özellikler',
    nav_how: 'Nasıl çalışır?',
    nav_pricing: 'Fiyatlar',
    nav_contact: 'İletişim',
    nav_dashboard: '🏠 Panel',
    nav_expenses: '💳 Harcamalar',
    nav_receipts: '📸 Makbuzlar',
    nav_summary: '📊 Finansal Özet',
    nav_settle: '🧮 Hesap Kapatma',
    nav_report: '📄 Rapor',
    nav_members: '👥 Üyeler ve Roller',
    nav_share: '🔗 Seyahati Paylaş',
    nav_settings: '⚙ Ayarlar',
    topbar_share: '🔗 Paylaş',
    topbar_add: '+ Harcama Ekle',
    sec_main: 'Ana',
    sec_expenses: 'Harcamalar',
    sec_analysis: 'Analiz',
    sec_members: 'Üyeler',
    kpi_total: 'Toplam Harcama',
    kpi_per: 'Kişi Başı',
    kpi_top: 'En Fazla Ödeyen',
    kpi_members: 'Üyeler',
    kpi_approx: 'yaklaşık',
    kpi_participant: 'katılımcı',
    page_dashboard: 'Panel',
    page_expenses: 'Harcamalar',
    page_summary: 'Finansal Özet',
    page_settle: 'Hesap Kapatma',
    page_report: 'Rapor',
    page_members: 'Üyeler ve Roller',
    page_share: 'Seyahati Paylaş',
    page_settings: 'Ayarlar',
    page_receipts: 'Makbuzlar',
    modal_add_exp: 'Harcama Ekle',
    modal_edit_exp: 'Harcamayı Düzenle',
    exp_name: 'Harcama Adı *',
    exp_amount: 'Tutar *',
    exp_paid_by: 'Ödeyen? *',
    exp_date: 'Tarih',
    exp_category: 'Kategori',
    exp_note: 'Not (isteğe bağlı)',
    exp_dist: 'Böl',
    exp_all: 'Herkes',
    exp_specific: 'Belirli kişiler',
    btn_save: 'Kaydet',
    btn_cancel: 'İptal',
    btn_delete: 'Sil',
    btn_edit: 'Düzenle',
    btn_add: 'Ekle',
    add_member: 'Üye Ekle',
    member_name: 'Üye Adı',
    member_phone: 'WhatsApp',
    member_role: 'Rol',
    add_member_btn: 'Yeni Üye',
    no_members: 'Henüz üye yok',
    organizer: 'Organizatör',
    settle_title: 'Hesap Kapatma',
    settle_note: 'Minimum transfer',
    settle_done: 'Hepsi kapandı! 🎉',
    settle_done_sub: 'Üyeler arasında bekleyen bakiye yok',
    no_trips: 'Henüz seyahat yok!',
    no_trips_sub: 'İlk seyahatinizi oluşturun',
    no_expenses: 'Henüz harcama yok',
    create_trip: '✈ Yeni Seyahat Oluştur',
    price_note: 'Sadece 249 AED — tek seferlik ödeme',
    share_copy: 'Kopyala',
    share_copied: '✓ Kopyalandı',
    share_wa: 'WhatsApp',
    send_btn: '💬 Gönder',
    settings_trip: '⚙ Seyahat Ayarları',
    settings_theme: '🎨 Sayfa Teması',
    settings_theme_hint: 'Renginizi seçin — her şey anında değişir',
    settings_save: 'Kaydet',
    settings_saved: 'Ayarlar kaydedildi ✓',
    settings_lang: '🌐 Dil',
    trip_name: 'Seyahat Adı',
    trip_dest: 'Hedef',
    trip_start: 'Başlangıç Tarihi',
    trip_end: 'Bitiş Tarihi',
    theme_men: '🔵 Güçlü — Derin ve sağlam',
    theme_women: '🌸 Zarif — Yumuşak ve rafine',
    theme_nature: '🌍 Doğa ve Seyahat',
    toast_added: 'Harcama eklendi',
    toast_edited: 'Harcama güncellendi',
    toast_deleted: 'Silindi',
    toast_copied: '✓ Bağlantı kopyalandı',
    toast_member_added: 'Üye eklendi',
    toast_error: 'Bir hata oluştu',
    toast_fill: 'Lütfen gerekli alanları doldurun',
    toast_theme: '✓ Tema değiştirildi',
    back: 'Geri', home: 'Ana Sayfa',
    create_btn: 'Seyahat Oluştur',
    user_role: '👑 Organizatör',
    paid: 'Ödedi:', owes: 'Borçlu:',
    total_exp: 'Toplam', exp_count: 'Harcamalar',
    per_person: 'Kişi Başı', trip_summary: 'Özet',
    status_active: '● Aktif', status_archived: '● Arşivlendi',
    members_lbl: 'üye', expenses_lbl: 'harcama',
    all_settled: 'Hepsi kapandı! Bekleyen bakiye yok.',
    loading: 'Seyahat verileri yükleniyor...',
    trip_not_found: 'Seyahat bulunamadı',
    trip_not_found_sub: 'Bağlantıyı kontrol edin veya organizatörle iletişime geçin',
    footer_link: 'Ücretsiz kaydol',
  },
};

/* ══════════════════════════════════════════════════════
   LANGUAGE ENGINE — محرك اللغة
══════════════════════════════════════════════════════ */

// اللغات المتاحة مع أعلامها
const REHLA_LANG_LIST = [
  {code:'ar', label:'العربية', flag:'🇸🇦'},
  {code:'en', label:'English', flag:'🇺🇸'},
  {code:'hi', label:'हिन्दी', flag:'🇮🇳'},
  {code:'fr', label:'Français', flag:'🇫🇷'},
  {code:'de', label:'Deutsch', flag:'🇩🇪'},
  {code:'tr', label:'Türkçe', flag:'🇹🇷'},
];

let _currentLang = localStorage.getItem('rehla_lang') || 'ar';
let _langDropOpen = false;

// الدالة الرئيسية للترجمة
function t(key) {
  const lang = REHLA_LANGS[_currentLang] || REHLA_LANGS['ar'];
  return lang[key] || REHLA_LANGS['ar'][key] || key;
}

// تطبيق اللغة على الصفحة كاملة
function applyLang(lang) {
  if (lang) _currentLang = lang;
  const L = REHLA_LANGS[_currentLang] || REHLA_LANGS['ar'];

  // اتجاه الصفحة
  document.documentElement.setAttribute('lang', _currentLang);
  document.documentElement.setAttribute('dir', L.dir);

  // تطبيق على العناصر بـ data-lang
  document.querySelectorAll('[data-lang]').forEach(el => {
    const key = el.getAttribute('data-lang');
    const val = t(key);
    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
      el.placeholder = val;
    } else {
      // احتفظ بالـ badge إذا موجود
      const badge = el.querySelector('.nav-badge,.lang-keep');
      el.textContent = val;
      if (badge) el.appendChild(badge);
    }
  });

  // تحديث زر اللغة
  const btn = document.getElementById('langDropBtn');
  if (btn) {
    const cur = REHLA_LANG_LIST.find(l => l.code === _currentLang);
    btn.innerHTML = `${cur?.flag || '🌐'} ${cur?.label || _currentLang} ▾`;
  }

  // حفظ
  localStorage.setItem('rehla_lang', _currentLang);
  sessionStorage.setItem('rehla_lang', _currentLang);
}

// فتح/إغلاق قائمة اللغة
function toggleLangDrop(e) {
  e?.stopPropagation();
  _langDropOpen = !_langDropOpen;
  const drop = document.getElementById('langDrop');
  if (drop) drop.style.display = _langDropOpen ? 'block' : 'none';
}

function selectLang(code) {
  _currentLang = code;
  applyLang(code);
  toggleLangDrop();
  // إعادة رسم الصفحة الحالية إن وجدت
  if (typeof showPage === 'function') {
    const active = document.querySelector('.nav-item.active');
    if (active) {
      const page = active.id?.replace('nav-', '');
      if (page) showPage(page);
    }
  }
  // إعادة رسم dashboard إن وجد
  if (typeof buildDashboard === 'function') buildDashboard();
}

// إنشاء زر اللغة المنسدل
function buildLangBtn(containerId) {
  const container = document.getElementById(containerId);
  if (!container) return;
  const cur = REHLA_LANG_LIST.find(l => l.code === _currentLang) || REHLA_LANG_LIST[0];
  container.style.position = 'relative';
  container.innerHTML = `
    <button id="langDropBtn" onclick="toggleLangDrop(event)" style="
      padding:7px 12px;border-radius:8px;background:rgba(255,255,255,.1);
      border:1px solid rgba(255,255,255,.2);color:rgba(255,255,255,.85);
      font-size:.78rem;font-weight:700;cursor:pointer;font-family:'Cairo',sans-serif;
      display:flex;align-items:center;gap:5px;white-space:nowrap;
      transition:all .2s;
    " onmouseover="this.style.background='rgba(255,255,255,.18)'"
       onmouseout="this.style.background='rgba(255,255,255,.1)'">
      ${cur.flag} ${cur.label} ▾
    </button>
    <div id="langDrop" style="
      display:none;position:absolute;top:calc(100% + 6px);
      ${document.documentElement.getAttribute('dir')==='rtl'?'right:0':'left:0'};
      background:#fff;border:1px solid #e2e8f0;border-radius:10px;
      box-shadow:0 8px 24px rgba(0,0,0,.15);z-index:9999;
      min-width:160px;overflow:hidden;
    ">
      ${REHLA_LANG_LIST.map(l => `
        <div onclick="selectLang('${l.code}')" style="
          display:flex;align-items:center;gap:9px;padding:10px 14px;
          cursor:pointer;font-size:.82rem;font-weight:600;
          color:${l.code===_currentLang?'#0891b2':'#334155'};
          background:${l.code===_currentLang?'#ecfeff':'transparent'};
          font-family:'Cairo',sans-serif;transition:background .15s;
        " onmouseover="if('${l.code}'!=='${_currentLang}')this.style.background='#f8fafc'"
           onmouseout="if('${l.code}'!=='${_currentLang}')this.style.background='transparent'">
          <span style="font-size:1.1rem">${l.flag}</span>
          <span>${l.label}</span>
          ${l.code===_currentLang?'<span style="margin-right:auto;color:#0891b2;font-size:.7rem">✓</span>':''}
        </div>`).join('')}
    </div>`;
  // إغلاق عند النقر خارجاً
  document.addEventListener('click', () => {
    _langDropOpen = false;
    const drop = document.getElementById('langDrop');
    if (drop) drop.style.display = 'none';
  });
}

// تطبيق اللغة فور تحميل الصفحة
document.addEventListener('DOMContentLoaded', () => {
  applyLang();
});
